---
language: python
python: "3.7"

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible-lint yamllint

script:
  - ansible-lint ansible/ansible.yml
  - yamllint .
