bpwp_dir_cache: cache
bpwp_dir_languages: languages
bpwp_dir_mu_plugins: mu-plugins
bpwp_dir_plugins: plugins
bpwp_dir_themes: themes
bpwp_dir_vendor: vendor
bpwp_dir_wordpress: wordpress
bpwp_my_name: bulletproof-wordpress
