---

bpwp_home_dir: "{{ playbook_dir }}/{{ bpwp_my_name }}"

bpwp_src:
  # languages
  languages_bpwp: "{{ bpwp_home_dir }}/{{ bpwp_dir_languages }}/"
  languages_user: "{{ playbook_dir }}/{{ bpwp_dir_languages }}/"
  # mu-plugins
  mu_plugins_bpwp: "{{ bpwp_home_dir }}/{{ bpwp_dir_mu_plugins }}/"
  mu_plugins_user: "{{ playbook_dir }}/{{ bpwp_dir_mu_plugins }}/"
  # plugins
  plugins_bpwp: "{{ bpwp_home_dir }}/{{ bpwp_dir_plugins }}/"
  plugins_user: "{{ playbook_dir }}/{{ bpwp_dir_plugins }}/"
  # themes
  themes_bpwp: "{{ bpwp_home_dir }}/{{ bpwp_dir_themes }}/"
  themes_user: "{{ playbook_dir }}/{{ bpwp_dir_themes }}/"
  # wordpress core
  wordpress: "{{ bpwp_home_dir }}/{{ bpwp_dir_wordpress }}/"
  # composer vendor
  vendor: "{{ playbook_dir }}/{{ bpwp_dir_vendor }}/"

bpwp_dest:
  languages: "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_dir_languages }}/"
  mu_plugins: "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_public_html_dir_name }}/{{ bpwp_wp_mu_plugins_dir_name }}/"
  plugins: "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_public_html_dir_name }}/{{ bpwp_wp_plugins_dir_name }}/"
  themes: "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_public_html_dir_name }}/{{ bpwp_wp_themes_dir_name }}/"
  uploads: "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_public_html_dir_name }}/{{ bpwp_wp_uploads_dir_name }}/"
  wordpress: "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_dir_wordpress }}/"
  vendor: "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_dir_vendor }}/"

bpwp_known_wp_core_files:
  - wp-includes/
  - index.php
  - wp-activate.php
  - wp-blog-header.php
  - wp-comments-post.php
  - wp-cron.php
  - wp-links-opml.php
  - wp-load.php
  - wp-login.php
  - wp-mail.php
  - wp-settings.php
  - wp-signup.php
  - wp-trackback.php
  - xmlrpc.php
