---

- name: "BPWP | Chmod directories & files in {{ chmod_chdir }}"  # noqa 301 305
  shell: "{{ item }}"
  args:
    chdir: "{{ chmod_chdir }}"
  with_items:
    - "{{ bpwp_chmod.dirs }}"
    - "{{ bpwp_chmod.files }}"
