---

- include_vars: bpwp-dir.yml

- pause:
    prompt: |-
                                ╓─────────────────────────╖
      ╒═════════════════════════╣ DEPLOYMENT CONFIRMATION ╠═════════════════════════
      │                         ╙─────────────────────────╜
      │
      │ Following local paths  will be uploaded to your remote server.
      │ Please make sure everything is correct before proceeding.
      │
      │ Warning! All remote files will be overwritten if target path exist.
      │
      ├─┬──────────────────────╼ Languages: {{ bpwp_dest.languages }}
      │ ├> {{ bpwp_project_dir_name}}{{ bpwp_src.languages_bpwp|replace(bpwp_project_home_dir, '') }}*
      │ └> {{ bpwp_project_dir_name}}{{ bpwp_src.languages_user|replace(bpwp_project_home_dir, '') }}*
      │
      ├─┬──────────────────────╼ MU Plugins: {{ bpwp_dest.mu_plugins }}
      │ ├> {{ bpwp_project_dir_name}}{{ bpwp_src.mu_plugins_bpwp|replace(bpwp_project_home_dir, '') }}*
      │ └> {{ bpwp_project_dir_name}}{{ bpwp_src.mu_plugins_user|replace(bpwp_project_home_dir, '') }}*
      │
      ├─┬──────────────────────╼ Plugins: {{ bpwp_dest.plugins }}
      │ ├> {{ bpwp_project_dir_name}}{{ bpwp_src.plugins_bpwp|replace(bpwp_project_home_dir, '') }}*
      │ └> {{ bpwp_project_dir_name}}{{ bpwp_src.plugins_user|replace(bpwp_project_home_dir, '') }}*
      │
      ├─┬──────────────────────╼ Themes: {{ bpwp_dest.themes }}
      │ ├> {{ bpwp_project_dir_name}}{{ bpwp_src.themes_bpwp|replace(bpwp_project_home_dir, '') }}*
      │ └> {{ bpwp_project_dir_name}}{{ bpwp_src.themes_user|replace(bpwp_project_home_dir, '') }}*
      │
      ├─┬──────────────────────╼ Wordpress Core
      │ ├> {{ bpwp_project_dir_name}}{{ bpwp_src.wordpress|replace(bpwp_project_home_dir, '') }}wp-admin/ => {{ bpwp_dest.wordpress }}{{ bpwp_wp_admin_dir_name }}/
      │ └> {{ bpwp_project_dir_name}}{{ bpwp_src.wordpress|replace(bpwp_project_home_dir, '') }}* => {{ bpwp_dest.wordpress }}*
      │
      ├─┬──────────────────────╼ Composer Vendor: {{ bpwp_dest.vendor }}
      │ └> {{ bpwp_project_dir_name}}{{ bpwp_src.vendor }}*
      │
      └─────────────────────────────────────────────────────────────────────────────

      Type "yes" to begin deployment
  register: user_confirmation

- fail: msg="Interrupted by user! Exiting."
  when: user_confirmation.user_input != 'yes'

- name: "BPWP | Ensure remote directories exist before uploading"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bpwp_remote_wordpress_home_dir }}"
    - "{{ bpwp_dest.languages }}"
    - "{{ bpwp_dest.mu_plugins }}"
    - "{{ bpwp_dest.plugins }}"
    - "{{ bpwp_dest.themes }}"
    - "{{ bpwp_dest.uploads }}"
    - "{{ bpwp_dest.wordpress }}"
    - "{{ bpwp_dest.vendor }}"

- include_tasks: upload-files.yml
  with_items:
    # languages
    - src: "{{ bpwp_src.languages_bpwp }}"
      dest: "{{ bpwp_dest.languages }}"
    - src: "{{ bpwp_src.languages_user }}"
      dest: "{{ bpwp_dest.languages }}"
    # mu-plugins
    - src: "{{ bpwp_src.mu_plugins_bpwp }}"
      dest: "{{ bpwp_dest.mu_plugins }}"
    - src: "{{ bpwp_src.mu_plugins_user }}"
      dest: "{{ bpwp_dest.mu_plugins }}"
    # plugins
    - src: "{{ bpwp_src.plugins_bpwp }}"
      dest: "{{ bpwp_dest.plugins }}"
    - src: "{{ bpwp_src.plugins_user }}"
      dest: "{{ bpwp_dest.plugins }}"
    # themes
    - src: "{{ bpwp_src.themes_bpwp }}"
      dest: "{{ bpwp_dest.themes }}"
    - src: "{{ bpwp_src.themes_user }}"
      dest: "{{ bpwp_dest.themes }}"
    # vendor
    - src: "{{ bpwp_src.vendor }}"
      dest: "{{ bpwp_dest.vendor }}"

- include_tasks: upload-wordpress-core.yml

- name: "BPWP | Ensure '{{ bpwp_wp_plugins_dir_name }}' directory exists"
  file:
    path: "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_public_html_dir_name }}/{{ bpwp_wp_plugins_dir_name }}"
    state: directory

- name: "BPWP | Create wp-config.php file outside '{{ bpwp_public_html_dir_name }}' directory"
  template:
    src: wp-config.php.j2
    dest: "{{ bpwp_remote_wordpress_home_dir }}/wp-config.php"
    force: true

- name: "BPWP | Configure crontab for Wordpress Cron"
  cron:
    name: "{{ bpwp_project_name|upper }}"
    minute: "{{ wp_cron_minute }}"
    hour: "{{ bpwp_cron_hour }}"
    day: "{{ wp_cron_day }}"
    month: "{{ bpwp_cron_month }}"
    weekday: "{{ bpwp_cron_weekday }}"
    job: "wget -q -O - {{ bpwp_project_public_url }}/wp-cron.php?doing_wp_cron >/dev/null 2>&1"
    state: present
  when: bpwp_custom_cron

- name: "BPWP | Disable crontab for Wordpress Cron"
  cron:
    name: "{{ bpwp_project_name|upper }}"
    state: absent
  when: not bpwp_custom_cron

- include_tasks: w3tc.yml
- include_tasks: smtp.yml
- include_tasks: autoupdates.yml

- include_tasks: rename-wp-admin.yml

- include_tasks: chmod.yml
  with_items:
    - "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_public_html_dir_name }}"
    - "{{ bpwp_dest.languages }}"
    - "{{ bpwp_dest.wordpress }}"
    - "{{ bpwp_dest.vendor }}"
  loop_control:
    loop_var: chmod_chdir
