---

- pause:
    prompt: |-
                                ╓─────────────────────────╖
      ╒═════════════════════════╣ DEPLOYMENT CONFIRMATION ╠═════════════════════════
      │                         ╙─────────────────────────╜
      │
      │ Following local paths  will be uploaded to your remote server.
      │ Please make sure everything is correct before proceeding.
      │
      │ Warning! All remote files will be overwritten if target path exist.
      │
      ├─┬──────────────────────╼ Languages: {{ dest_languages }}
      │ ├> {{ src_languages_bfwp }}*
      │ └> {{ src_languages_user }}*
      │
      ├─┬──────────────────────╼ MU Plugins: {{ dest_mu_plugins }}
      │ ├> {{ src_mu_plugins_bfwp }}*
      │ └> {{ src_mu_plugins_user }}*
      │
      ├─┬──────────────────────╼ Plugins: {{ dest_plugins }}
      │ ├> {{ src_plugins_bfwp }}*
      │ └> {{ src_plugins_user }}*
      │
      ├─┬──────────────────────╼ Themes: {{ dest_themes }}
      │ ├> {{ src_themes_bfwp }}*
      │ └> {{ src_themes_user }}*
      │
      ├─┬──────────────────────╼ Wordpress Core
      │ ├> {{ src_wordpress_bfwp }}wp-admin/ => {{ dest_wordpress }}{{ bpwp_wp_admin_dir_name }}/
      │ └> {{ src_wordpress_bfwp }}* => {{ dest_wordpress }}*
      │
      ├─┬──────────────────────╼ Composer Vendor: {{ dest_vendor }}
      │ └> {{ src_vendor_user }}*
      │
      └─────────────────────────────────────────────────────────────────────────────

      Type "yes" to begin deployment
  register: user_confirmation

- fail: msg="Interrupted by user! Exiting."
  when: user_confirmation.user_input != 'yes'

- name: "BPWP | Ensure remote directories exist before uploading"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bpwp_remote_wordpress_home_dir }}"
    - "{{ dest_languages }}"
    - "{{ dest_mu_plugins }}"
    - "{{ dest_plugins }}"
    - "{{ dest_themes }}"
    - "{{ dest_wordpress }}"
    - "{{ dest_vendor }}"

- include_tasks: upload-files.yml
  with_items:
    # languages
    - src: "{{ src_languages_bfwp }}"
      dest: "{{ dest_languages }}"
    - src: "{{ src_languages_user }}"
      dest: "{{ dest_languages }}"
    # mu-plugins
    - src: "{{ src_mu_plugins_bfwp }}"
      dest: "{{ dest_mu_plugins}}"
    - src: "{{ src_mu_plugins_user }}"
      dest: "{{ dest_mu_plugins}}"
    # plugins
    - src: "{{ src_plugins_bfwp }}"
      dest: "{{ dest_plugins }}"
    - src: "{{ src_plugins_user }}"
      dest: "{{ dest_plugins }}"
    # themes
    - src: "{{ src_themes_bfwp }}"
      dest: "{{ dest_themes }}"
    - src: "{{ src_themes_user }}"
      dest: "{{ dest_themes }}"
    # vendor
    - src: "{{ src_vendor_user }}"
      dest: "{{ dest_vendor }}"

- include_tasks: upload-wordpress-core.yml

- name: "BPWP | Ensure '{{ bpwp_wp_plugins_dir_name }}' directory exists"
  file:
    path: "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_public_html_dir_name }}/{{bpwp_wp_plugins_dir_name}}"
    state: directory

- name: "BPWP | Create wp-config.php file outside {{ bpwp_public_html_dir_name }} directory"
  template:
    src: wp-config.php.j2
    dest: "{{ bpwp_remote_wordpress_home_dir }}/wp-config.php"
    force: true

- name: "BPWP | Configure Wordpress to look for wp-config.php in new place"
  copy:
    content: "<?php require_once ABSPATH.'..'.DIRECTORY_SEPARATOR.'wp-config.php'; require_once ABSPATH . 'wp-settings.php';"
    dest: "{{ bpwp_remote_wordpress_home_dir }}/{{ bpwp_public_html_dir_name }}/wp-config.php"
    force: true

- name: "BPWP | Configure Wordpress Cron"
  cron:
    name: "{{ bpwp_project_name|upper }}"
    minute: "{{ wp_cron_minute }}"
    hour: "{{ bpwp_cron_hour }}"
    day: "{{ wp_cron_day }}"
    month: "{{ bpwp_cron_month }}"
    weekday: "{{ bpwp_cron_weekday }}"
    job: "wget -q -O - {{ bpwp_project_url }}/wp-cron.php?doing_wp_cron >/dev/null 2>&1"
    state: "{% if bpwp_custom_cron) %}present{% else %}absent{% endif %}"

- name: "BPWP | Force disabling auto-updates mechanism"
  copy:
    src: bpwp-force-disable-autoupdates.php
    dest: "{{ dest_mu_plugins }}bpwp-force-disable-autoupdates.php"
    force: true
  when: bpwp_wp_disable_autoupdates

- name: "BPWP | Ensure auto-updates are not forced to be disabled"
  file:
    path: "{{ dest_mu_plugins }}bpwp-force-disable-autoupdates.php"
    state: absent
  when: not bpwp_wp_disable_autoupdates
