---

- name: "BPWP | Prepare wp-admin file list to upload"
  set_fact:
    bpwp_wp_core_paths_to_upload: "{{ bpwp_wp_core_paths_to_upload|default([]) + [{ 'src': bpwp_src.wordpress+item, 'dest': bpwp_dest.wordpress+item }] }}"  # yamllint disable-line rule:line-length
  with_items: "{{ bpwp_known_wp_core_files }}"

- name: "BPWP | Prepare wp-admin files to be uploaded"
  set_fact:
    bpwp_wp_core_paths_to_upload: "{{ bpwp_wp_core_paths_to_upload + [{ 'src': bpwp_src.wordpress+'wp-admin/', 'dest': bpwp_dest.wordpress+bpwp_wp_admin_dir_name+'/' }] }}"  # yamllint disable-line rule:line-length

- include_tasks: upload-files.yml
  with_items: "{{ bpwp_wp_core_paths_to_upload }}"

- set_fact:
    bpwp_known_wp_core_files: "{{ bpwp_known_wp_core_files + ['wp-admin/'] }}"
  when: bpwp_wp_admin_dir_name == 'wp-admin'

- set_fact:
    bpwp_known_wp_core_files: "{{ bpwp_known_wp_core_files + [bpwp_wp_admin_dir_name+'/'] }}"
  when: bpwp_wp_admin_dir_name != 'wp-admin'

- include_tasks: single-wp-admin-item.yml
  with_items: "{{ bpwp_known_wp_core_files }}"
